name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Или master, в зависимости от вашей основной ветки

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: 'Checkout' 
        uses: actions/checkout@v4

      - name: 'Set up Node.js'
        uses: actions/setup-node@v4
        with:
          node-version: '20' # Используйте версию Node.js, которая вам нужна

      - name: 'Install dependencies (using npm ci for clean install)'
        run: npm ci # Use npm ci for clean installs in CI/CD

      - name: 'Debug: Print PATH environment variable'
        run: echo "$PATH"

      - name: 'Debug: List node_modules contents'
        run: ls -l node_modules

      - name: 'Debug: List node_modules/.bin contents'
        run: ls -l node_modules/.bin

      - name: 'Debug: Print npm version and cache path'
        run: |
          npm -v
          npm config get cache

      - name: 'Debug: Print package.json scripts'
        run: cat package.json

      - name: 'Build project' # Reverted to npm run build
        run: npm run build

      - name: 'Deploy to GitHub Pages'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Каталог, который будет опубликован
          # Если ваш сайт опубликован в подпапке (например, /bike-unity/),
          # убедитесь, что в vite.config.ts base: '/bike-unity/' 